# Generated by Django 2.1.5 on 2020-01-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_wallstreetjournalheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='theVergeHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
    ]
