# Generated by Django 2.1.5 on 2020-02-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_thevergeheadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastupdated',
            old_name='time',
            new_name='minutes',
        ),
    ]
