# Generated by Django 2.1.5 on 2020-02-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200203_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcrunchheadline',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
