# Generated by Django 2.1.5 on 2020-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_techcrunchheadline_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='thevergeheadline',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallstreetjournalheadline',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
