# Generated by Django 2.1.5 on 2020-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_auto_20200227_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinsiderheadline',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seekingalphaheadline',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techcrunchheadline',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallstreetjournalheadline',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wiredheadline',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
