# Generated by Django 3.0.4 on 2020-03-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20200227_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastupdated',
            name='hours',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
