# Generated by Django 3.0.4 on 2020-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_lastupdated_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastupdated',
            name='hours',
        ),
        migrations.AlterField(
            model_name='lastupdated',
            name='minutes',
            field=models.IntegerField(),
        ),
    ]
